### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by ZhouCX117** [hsiangyuzhao/RCPS#1]
Hi, thanks for your excellent work. When will you release the code?

**Comment by hsiangyuzhao** [comment]
Hi, thanks for your interest to our work. The compelete code will be released soon as the paper is accepted, while the code for inference will be released soon when the code is reformated.

**Comment by Jiawei0o0** [comment]
Actually， a part code may be found on this paper "Uncertainty-aware pseudo-label and consistency for semi-supervised
medical image segmentation".  The part of this work (URP, utilize kl to weight the consisitency loss) is excalty the same as this paper.

**Comment by hsiangyuzhao** [comment]
We are working to reformat the main code and required scripts for data preparation. Progress could be found in the readme file.

**Comment by hsiangyuzhao** [comment]
Full code has been published.
