### ISSUE TITLE
LA数据集链接打不开

### ISSUE THREAD

**Issue by BinYCn** [hsiangyuzhao/RCPS#10]
你好，感谢您的工作和分享。您提供的LA数据集的链接无法打开，请问方便使用邮箱或者网盘给我一份吗？非常感谢！
我的邮箱号是904363330@qq.com

**Comment by hsiangyuzhao** [comment]
Sorry for the late reply. It seems that the official website is out of service. I am not sure whether this is merely a technical issue or the website is closed down. Unfortunately, according to the rules, we are not allowed to redistribute the data. Perhaps you may look for the data at https://academictorrents.com.

Thank you again for your interest in our research work.

**Comment by hsiangyuzhao** [comment]
Hi @BinYCn ,

You may find the data at https://www.cardiacatlas.org/atriaseg2018-challenge/atria-seg-data/.
