### ISSUE TITLE
How can I resolve this question? Thank you

### ISSUE THREAD

**Issue by wm-xmm** [hsiangyuzhao/RCPS#12]
![image](https://github.com/hsiangyuzhao/RCPS/assets/76035330/57a6d403-890e-4c95-a4d5-0360219ed000)

**Comment by hsiangyuzhao** [comment]
The error indicates that the relative path does not exist, you should check whether the folder exists or not. Or this may be because Windows OS use '\\' rather '/' for splitting the path.

**Comment by wm-xmm** [comment]
I created the data folder according to this standard, thank you

![image](https://github.com/hsiangyuzhao/RCPS/assets/76035330/728441be-362f-4007-ae8d-8fd5d33ea726)
