### ISSUE TITLE
关于数据

### ISSUE THREAD

**Issue by yyyyy-aa** [hsiangyuzhao/RCPS#13]
Thank you for your If you encounter issues downloading the data, you may find the same data at : https://academictorrents.com/details/80ecfefcabede760cdbdf63e38986501f7becd49
Please note that the orientation of the data downloaded from this link is not correct, please correct them manually. 
请问这里的 "correct them manually"具体指什么呢？

**Comment by hsiangyuzhao** [comment]
The orientation of the data downloaded from this link is not correct, which means that if you read the image and label together, you will find the organs and labels are mismatching. Thus, you need to correct them manually with nibabel or SimpleITK.

**Comment by yyyyy-aa** [comment]
Hello, thank you for your patience and answer. At present, I have only downloaded the Atrial Segmentation dataset. May I ask whether I should first run prepare_la_dataset.py or preprocess_data before training? My current data folder is as follows.
-RCPS-main
   -data
       -la_data
                 -Training Set
                 -Testing Set
                 preprocess_data.py
                 Unet.py
       la.csv
       pancreas.csv
       prepare_la_dataset.py
       prepare_pancreas_dataset.py
       preprocess_data.py
       Unet.py

**Comment by yyyyy-aa** [comment]
under RCPS-main/data/:
-la_data
la.csv
pancreas.csv
prepare_la_dataset.py
prepare_pancreas_dataset.py
preprocess_data.py
Unet.py


under la_data folder:
-Training Set
-Testing Set
preprocess_data.py
Unet.py

**Comment by codesheepZ** [comment]
la_data放在data文件下面

**Comment by codesheepZ** [comment]
bro，你的la_data放错了位置，要放在data下面，然后再运行那两个脚本

**Comment by codesheepZ** [comment]
兄弟，你的la_data放错了位置，要把数据放在下面，然后再运行那两个脚本
而且la_data就直接放数据集了，不是一整个文件，我昨天看你的这个存放位置给我误导了

**Comment by zorcanz** [comment]
bro，你的la_data放错了位置，直接放在data文件夹里面，然后再运行那两个脚本
la_data就直接放数据集了，不是整个文件，我昨天看你的这个文件位置给我误导了

**Comment by yyyyy-aa** [comment]
> bro，你的la_data放错了位置，直接放在data文件夹里面，然后再运行那两个脚本 la_data就直接放数据集了，不是整个文件，我昨天看你的这个文件位置给我误导了

我的la_data文件夹就在data文件夹下，然后la_data下有解压出的训练和测试数据集，这样是对的吗，只需要运行prepare_la_dataset.py就行了嘛

**Comment by codesheepZ** [comment]
对

**Comment by yyyyy-aa** [comment]
> 对

请问你[Pancreas-CT]的数据是怎么处理的啊
