### ISSUE TITLE
全监督（ratio = 1）训练出现loss Nan的问题

### ISSUE THREAD

**Issue by yyyyy-aa** [hsiangyuzhao/RCPS#16]
你好，我在全监督（ratio = 1）训练时出现了nan的问题，如下图所示：
![nan](https://github.com/hsiangyuzhao/RCPS/assets/162097335/1ab7bade-f3f7-4108-a4b8-58b0d098edd8)
请问需要改哪里的代码，我的实验设置与论文的相同。

**Comment by hsiangyuzhao** [comment]
Actually the released code base does not support "fully supervision". If you set `labeled_ratio=1.0`, then you will have an empty unlabeled dataset, which could leads to NaNs or Nulls during training. You are required to remove the unlabeled loader as well as related losses if you do so.
