### ISSUE TITLE
代码第10个epoch报错（全监督-RATIO=0.1）

### ISSUE THREAD

**Issue by yyyyy-aa** [hsiangyuzhao/RCPS#17]
![image](https://github.com/hsiangyuzhao/RCPS/assets/162097335/6dbb3187-5b5c-411c-bcc1-622c1b0e7cba)

在按照提示进行pip install moviepy imageio后，显示已有

![image](https://github.com/hsiangyuzhao/RCPS/assets/162097335/bc6fa0b8-4f11-4a51-8134-ef2cde4fa613)

但再次运行train.py仍报相同错误如第一张图所示
请问还需要怎么改

**Comment by hsiangyuzhao** [comment]
I would suggest you test that whether your moviepy and imageio works fine. Start a python script and import these two packages and test some basic functions. If both packages work fine, there may be something wrong with wandb, and I would suggest you comment the lines involving video saving.
