### ISSUE TITLE
Test mould and make predictions

### ISSUE THREAD

**Issue by Kelvin-hzm** [hsiangyuzhao/RCPS#20]
Hello hsiangyuzhao! I saw the Figure 2 in your paper that has blue lines denote the predictions and I wonder how can I get that cut line after training my own mould? In other word, I wanna test the train mould I got and make some predictions. Is it mark red in the train_visualization?

**Comment by hsiangyuzhao** [comment]
Visualization code is not provided in the open source code. 

If you want to make some visualizations using contours, you may use [`skimage.segmentation.find_boundaries`](https://scikit-image.org/docs/stable/api/skimage.segmentation.html#skimage.segmentation.find_boundaries) function, which might be useful.

**Comment by Kelvin-hzm** [comment]
Sorry for disturbing you again, I try to use find_boundaries function but fail to get some result when I occur to make model predition, would you mind giving me more details?

**Comment by hsiangyuzhao** [comment]
Hi @Kelvin-hzm 

You could run `find_boundaries` function at model prediction to find the contour, and then you could assign a RGB value to these regions at the corresponding image. The pseudo code might look like this:

```python
# image: (H, W, 3), a 3-channel RGB image slice
# pred: (H, W), same shape with image
contours = find_boundaries(pred)
image[contours] = (255, 0, 0)  # red contour
```

I would suggest you generate the contour slice by slice for better visualization quality.

**Comment by Kelvin-hzm** [comment]
Thanks!
