### ISSUE TITLE
About experiment results

### ISSUE THREAD

**Issue by yyyyy-aa** [hsiangyuzhao/RCPS#21]
Sorry to bother you again. There are some differences between my experimental results and yours. I want to know that is the experimental result of the following figure in the article obtained through the experimental scenario of 'Training with different label ratio '?
![image](https://github.com/hsiangyuzhao/RCPS/assets/162097335/b87b8979-572a-49e1-b92f-c7a5e1cdedd8)

Following your experimental instructions, I obtained the following experimental results of the ' Training with different label ratio ' experimental scenario, which seems to be different from yours.

' Training with different label ratio ' experimental scenario：
ratio=0.1
bg_dice: 0.9895 ± 0.0075;  la_dice: 0.8736 ± 0.0516;  bg_hd95: 2.0215 ± 1.2702;  la_hd95: 11.6413 ± 11.1788;  bg_asd: 0.3815 ± 0.1997;  la_asd: 2.7246 ± 1.6591;

ratio=0.2
bg_dice: 0.9918 ± 0.0049;  la_dice: 0.9007 ± 0.0313;  bg_hd95: 1.668 ± 0.8762;  la_hd95: 6.5163 ± 3.4624;  bg_asd: 0.287 ± 0.1349;  la_asd: 1.9518 ± 0.8151;

**Comment by hsiangyuzhao** [comment]
Sorry for the late reply. Please refer to [#issue5](https://github.com/hsiangyuzhao/RCPS/issues/5) for more details about reproductivity.

Similar hardware and running environments are required to obtain a good reproduction of our results.
