### ISSUE TITLE
LA dataset

### ISSUE THREAD

**Issue by smallkaka** [hsiangyuzhao/RCPS#3]
At present, I am unable to obtain LA dataset. Can you share it with me? I will only be doing academic research, and this is my student email address shiya.xu@cumt.edu.cn

**Comment by Leesoon1984** [comment]
Can you share the LA dataset? This is my student email address [leesoon@bupt.edu.cn](mailto:leesoon@bupt.edu.cn)

**Comment by Leesoon1984** [comment]
> At present, I am unable to obtain LA dataset. Can you share it with me? I will only be doing academic research, and this is my student email address [shiya.xu@cumt.edu.cn](mailto:shiya.xu@cumt.edu.cn)

Can you share the LA dataset? This is my student email address [leesoon@bupt.edu.cn](mailto:leesoon@bupt.edu.cn)
