### ISSUE TITLE
数据处理

### ISSUE THREAD

**Issue by Leesoon1984** [hsiangyuzhao/RCPS#7]
请问数据是怎么处理的呢？

**Comment by hsiangyuzhao** [comment]
Detailed description has been clearly provided in our readme profile. Please follow the description to download the data and run the two scripts in the `data` folder.

**Comment by Leesoon1984** [comment]
> 下载数据的格式，与数据处理代码，似乎对不上？

**Comment by hsiangyuzhao** [comment]
> 下载数据的格式，与数据处理代码，似乎对不上？

For pancreas CT dataset, TCIA provides data in DICOM format, you could transform them into NIFTI. 
Or you could download from this url as well: https://academictorrents.com/details/80ecfefcabede760cdbdf63e38986501f7becd49

Please note that the orientation of the data downloaded from this link is not correct, please correct them manually.

**Comment by Leesoon1984** [comment]
> > 下载数据的格式，与数据处理代码，似乎对不上？
> 
> For pancreas CT dataset, TCIA provides data in DICOM format, you could transform them into NIFTI. Or you could download from this url as well: https://academictorrents.com/details/80ecfefcabede760cdbdf63e38986501f7becd49
> 
> Please note that the orientation of the data downloaded from this link is not correct, please correct them manually.

非常感谢
