### ISSUE TITLE
about requirements

### ISSUE THREAD

**Issue by wwhXX** [hsiangyuzhao/RCPS#9]
你好，感谢您的工作和分享。在尝试复现你们工作时我需要申请对应环境的服务器，但是我没有在文档中看到代码的requirements，能麻烦您告知吗？

**Comment by hsiangyuzhao** [comment]
Hi @wwhXX ,
Thanks for the interest in our work. The packages needed for our repo are pasted below:
```
numpy
pandas
matplotlib
pyyaml
wandb
pytorch
torchvision
monai
nibabel
tqdm
```
